### ISSUE TITLE
How to download full ini?

### ISSUE THREAD

**Issue by TomThak** [browscap/browscap-php#152]
Hello,
I use browscap as described with downloaded cache file.
But if I look at http://browscap.org/ua-lookup I can see, that you can provide more info, than my browscap ini returns. I used $browscap->doAutoUpdate to download the ini. On the download page I can see, that for PHP there are 3different types of ini - lightweight, full and some standard.
For example I do not have object property "platform_description".
I only have following properties of browscap object:

["browser_name"]
["browser_name_regex"]
["browser_name_pattern"]
["Parent"]
["Platform"]
["Comment"]
["Browser"]
["Browser_Maker"]
["Version"]
["MajorVer"]
["Device_Type"]
["Device_Pointing_Method"]
["MinorVer"]
["isMobileDevice"]
["isTablet"]
["Crawler"]

But many of them are missing if I compare it with UAlookup page. At least I would love to get platform_description.

Thanks for help!

**Comment by asgrim** [comment]
Judging by your phrasing, I'm guessing you're using Browscap 2.x branch. In which case you can override the URL by setting the `remoteIniUrl` setting, like so:

```php
<?php

$browscap = new \phpbrowscap\Browscap(/* ...cache dir... */);
$browscap->remoteIniUrl = 'http://browscap.org/stream?q=Full_PHP_BrowsCapINI';
```

Note that due to the larger amount of memory required to run this, we recommend following instructions here: https://github.com/browscap/browscap-php/tree/2.x#recommended-setup (setting up as a cron job).

**Comment by TomThak** [comment]
Ah, ok thanks!
