### ISSUE TITLE
memory exhausted errors

### ISSUE THREAD

**Issue by whiteatom** [browscap/browscap-php#20]
I have been a long time users of Browscap v1.0, however, I decided to upgrade to the newest version. Now I am getting constant out of memory errors in the Browscap script. 

Fatal error: Allowed memory size of 201326592 bytes exhausted (tried to allocate 32 bytes) in /www/tracker/dev/incs/Browscap.php on line 683

I have had to increase the memory limit 3 times (up to 256MB) to get it to work. 

Why is this new script so inefficient on memory? is there a fixed planned as it is not sustainable to run a production server with a single php script requiring that much memory.

**Comment by ve3** [comment]
I have same memory problem.

**Comment by frederikbosch** [comment]
@ve3 start using `yzalis/ua-parser`

**Comment by asgrim** [comment]
@frederikbosch @ve3 or, feel free to submit a PR to make it better :) thanks!

**Comment by asgrim** [comment]
In fact, by the way the `3.x` branch should be much more memory efficient, so I recommend you use this instead :) https://github.com/browscap/browscap-php/tree/3.x

**Comment by jaydiablo** [comment]
The crossjoin browscap parser https://github.com/crossjoin/Browscap is A LOT more memory efficient, and actually quite a bit faster than browscap-php, as outlined in this ticket: https://github.com/crossjoin/Browscap/issues/12

And it still uses browscap data, which is more complete than what ua_parser offers, IMO.

**Comment by asgrim** [comment]
@jaydiablo is that vs the `3.x` branch or existing stable (2.0.5)?

**Comment by jaydiablo** [comment]
@asgrim The benchmarks in that ticket are just against the latest 2.x version (2.0.5 at the time of that writing), however I have run the browscap tests against the 3.x branch as well, just never posted the results.

Here are some results that I just ran on my mac, all are fresh checkouts of the respective master branch.

browscap-php dev-master (2.x):
>Time: 11.35 minutes, Memory: 715.25Mb
>
>OK, but incomplete, skipped, or risky tests!
>Tests: 9210, Assertions: 178223, Skipped: 2413.

browscap-php 3.x-dev:
>Time: 18.14 minutes, Memory: 194.75Mb
>
>OK, but incomplete, skipped, or risky tests!
>Tests: 9210, Assertions: 178223, Skipped: 2413.

crossjoin dev-master
>Time: 2.47 minutes, Memory: 163.00Mb
>
>OK, but incomplete, skipped, or risky tests!
>Tests: 9210, Assertions: 178223, Skipped: 2413.

browscap-php 3 does use substantially less memory than browscap 2 in these tests, which is good to see, but it's actually worse in speed. It's not just during the cache generation either, as you can watch the tests run and see that it takes a while on individual tests after the cache building steps.  

I've also modified the useragent benchmark project a little bit to add browscap 3.x, here are the results (note that the times and memory shown here are to process the user agents in the file. The cache building is done as a separate step prior to running the benchmark). These are run on a linux virtual machine, I only note this because my mac has an SSD drive, the linux machine has magnetic.

>Running Benchmark using agents in top-200-last-24.txt
>Benchmarking browscap-php ...	26.142086secs 	90MB
>Benchmarking browscap-php-3 ...	61.493058secs 	26.25MB
>Benchmarking crossjoin-browscap ...	2.1639847secs 	1.75MB

>Running Benchmark using agents in top-1000-last-7days.txt
>Benchmarking browscap-php ...	130.32173secs 	35.75MB
>Benchmarking browscap-php-3 ...	273.94758secs 	26.5MB
>Benchmarking crossjoin-browscap ...	10.996641secs 	4.5MB

>Running Benchmark using agents in ua-list-all.txt
>Benchmarking browscap-php ...	73.313462secs 	35.25MB
>Benchmarking browscap-php-3 ...	88.502528secs 	26.25MB
>Benchmarking crossjoin-browscap ...	3.2833108secs 	2.5MB

>Running Benchmark using agents in ua-list-100-sample01.txt
>Benchmarking browscap-php ...	14.938440secs 	35.25MB
>Benchmarking browscap-php-3 ...	22.302146secs 	26.25MB
>Benchmarking crossjoin-browscap ...	0.5970990secs 	1.25MB

One of the modifications that I made to the benchmark utility was to time each useragent lookup individually and log to a CSV file (I mention this in the crossjoin ticket).  This allows me to build a comparison CSV to see which useragents each library is faster or slower at.  Here's that CSV for the "top-200-last-24.txt" run above:  https://docs.google.com/spreadsheets/d/1mtISknvOyC7KurRVeAeNFtq7ZZpuremkjITjHDlCF7I/pub?gid=1776088907&single=true&output=csv

Certainly the memory use of Browscap 3 is looking better than 2, but at a cost for performance (as it is in its present state).  The crossjoin parser excels at memory use, and speed.

I have branches of browscap/browscap to run the tests, a simple clone of these should allow you to replicate the tests in your environment:

https://github.com/jaydiablo/browscap
https://github.com/jaydiablo/browscap/tree/crossjoin
https://github.com/jaydiablo/browscap/tree/browscap-php-3

The browscap 3.x one is mostly a copy of @mimmi20 's refactor branch, but I changed the formatter that it uses.  If you see something incorrect with the setup/config of browscap 3 in that branch, let me know.  As far as I can tell it generates the cache files, so I assume it's using them for the useragent parsing.

I'd like to contribute back some of the changes I've made to the useragent benchmark utility, but I have to clean it up a little bit.  It requires a bit of hoop jumping to get browscap-php and browscap-php 3 running at the same time (composer related) which I don't think can be committed back upstream, but a branch to replace browscap-php with browscap-php 3 could be made.

**Comment by jaydiablo** [comment]
I looked around a bit at the 3.x code, and it does look like a lot of it is based on crossjoin, particularly the storage of the patterns/iniparts in separated cache files.

I ran a profile of 3.x with blackfire against the slowest useragent it processed in that csv I linked to above:  https://blackfire.io/profiles/bdb371a4-11cb-428f-8281-66c9079ff64d/graph

Like I was seeing with crossjoin when I first started testing with it, the majority of the time is spent in preg_match, and preg_match is called a lot of times (nearly 800 in this case).  I suspect you'll see the most gains in speed by looking at reducing the number of patterns that are stored in the cache files, mainly be "compressing" them (as it's called in browscap-php 2.x's source), i.e., removing the digits from the patterns and replacing with regex \d, then removing any patterns that are the same.  This was the biggest win for me when I was trying to optimize crossjoin: https://github.com/crossjoin/Browscap/commit/2ee9663bd4b971c658d87f33fe780858580f7bd4 (the digit replacement in that commit is a bit overzealous, and causes tests to fail, which was fixed later https://github.com/crossjoin/Browscap/commit/afd9f8eaec3fe506ed864a93a536e2370b570922).

I'd love to help, but have spent too much time on browscap related tasks lately.  We're VERY happy with crossjoin, but do dislike the idea of there being two (php) parsers out there.  I'd love to see browscap 3 be the one true parser, but in order for that to happen I think the performance has to get better (at least for us).

**Comment by asgrim** [comment]
@jaydiablo thanks very much for your feedback. I've created a new issue in #101 to investigate the performance of the `3.x` branch.

FWIW, I don't mind there being multiple parsers, it promotes a healthy ecosystem imo :) however, we'll only "officially" support stuff on github.com/browscap (although we'll do our best for other stuff too!)
