### ISSUE TITLE
Cannot get browser version since Firefox update to v56

### ISSUE THREAD

**Issue by EtienneDh** [browscap/browscap-php#224]
Hi,

I recently discovered this library while working on a project, so first thanks for providing us a better way to detect browser.

However it seems like checking version for firefox is broken since last update (v56) as it returns "0".

**Comment by jaydiablo** [comment]
Thanks for the report, yes, Firefox 56 isn't detected yet. Support for that version was added recently but hasn't made its way to a released version of the data files yet. Once `6025` of the data files are released, Firefox 56 will detect properly.

Added in this commit: https://github.com/browscap/browscap/commit/0673e056fb10564e1c17235a185397c723c2f30f#diff-106a5587c93991de9fade2f14e69445a

`6025` should be released soon, as it's been a couple of months since `6024` came out.

Also, fyi, if there are missing browsers/platforms/versions/devices, issues should be reported against this library: https://github.com/browscap/browscap/ Which is the repo for all of the source files that build the INI file that this parser uses.
