### ISSUE TITLE
No $return_array option.

### ISSUE THREAD

**Issue by cihantas** [browscap/browscap-php#252]
https://github.com/browscap/browscap-php/blob/6ab240a1c0f8a94a4838f9c7296a510f4afbab1a/src/Browscap.php#L103-L104

There's not parameter $return_array that I can pass to `->getBrowser()`. Is this a bug or am I missing something?

**Comment by jaydiablo** [comment]
I think this is probably just a documentation issue (looks like that parameter was removed long ago. It was in the 2.0 implementation: https://github.com/browscap/browscap-php/blob/2.x/src/phpbrowscap/Browscap.php#L297 but was removed by the first alpha version of the 3.0 release: https://github.com/browscap/browscap-php/blob/3.0.0-alpha.1/src/Browscap.php#L285)

Since `getBrowser` returns a `stdClass`, you can just cast that to an array, like so:

```
$browser = (array) $browscap->getBrowser('user-agent');
```
example: https://3v4l.org/mRXqA
