### ISSUE TITLE
Does 7.2 require roave/doctrine-simplecache

### ISSUE THREAD

**Issue by dragsu** [browscap/browscap-php#666]
`roave/doctrine-simplecache` is not a required dependency in the 7.2 release. However,  when I try to use the 7.2 version in `https://github.com/MISP` I get,

```
[Error] Class 'Doctrine\Common\Cache\FilesystemCache' not found
[Error] Class 'Roave\DoctrineSimpleCache\SimpleCacheAdapter' not found
```

I managed to resolve it by installing `roave/doctrine-simplecache`.

**Comment by asgrim** [comment]
Thanks @dragsu - couple of points;

 - I  believe this is expected behaviour; you are not necessarily required to use a specific cache implementation, we depend on `"psr/simple-cache": "^2.0.0 || ^3.0.0"` so any compatible cache could be used. The [`README.md`](https://github.com/browscap/browscap-php/blob/7.5.x/README.md) itself suggests a couple of ways in the examples
 - General suggestion to use use the latest version, if possible
