### ISSUE TITLE
after updating from 2.0B to 2.0.4 I have an error regarding cache.lock

### ISSUE THREAD

**Issue by hamburger123456** [browscap/browscap-php#72]
<br />
<b>Fatal error</b>:  Uncaught exception 'phpbrowscap\Exception' with message 'temporary file /www/htdocs/abc/123/cache/cache.lock already exists' in /www/htdocs/abc/123/scripts/Browscap.php:530
Stack trace:
#0 /www/htdocs/abc/123/scripts/Browscap.php(300): phpbrowscap\Browscap-&gt;updateCache()
#1 /www/htdocs/abc/123/collect.php(106): phpbrowscap\Browscap-&gt;getBrowser(NULL, true)
#2 /www/htdocs/abc/123/collect.php(39): pageview()
#3 {main}
  thrown in <b>/www/htdocs/abc/123/scripts/Browscap.php</b> on line <b>530</b><br />

Whats to do?

**Comment by mimmi20** [comment]
You could run this in a separate process. You may have to remove the cache.lock file in your cache directory.

$browscap = new phpbrowscap\Browscap($cacheDir);
$browscap->updateCache();
After this you should add the line

$bc->doAutoUpdate = false;

to your script.

Please look at #20 for additional information.

**Comment by mimmi20** [comment]
The error occurs when 2 processes try to create the cache at the same time.

You should use two processes:
1. One for creating and updating the cache
2. One for detecting without updating the cache

**Comment by asgrim** [comment]
@hamburger123456 We strongly advice disabling auto-update in all scenarios, otherwise when a visitor visits your website when a new version has just been released, the visitor will have to wait for the download of the file in the background, and then the processing.

In fact, in the 3.x branch that is work in progress, this is the *only* way to operate browscap-php :)
